apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiaGdraW0yNDEzIiwicGFzc3dvcmQiOiJnaHBfVEx4aEFWbXFIM1NDbEZhczd0VmRBbVJxYVhnZGZ3MU54UTV5IiwiZW1haWwiOiJoZ2tpbTI0MTNAd2lzZW51dC5jby5rciIsImF1dGgiOiJhR2RyYVcweU5ERXpPbWRvY0Y5VVRIaG9RVlp0Y1VnelUwTnNSbUZ6TjNSV1pFRnRVbkZoV0dka1puY3hUbmhSTlhrPSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: hgkim2413
type: kubernetes.io/dockerconfigjson
